language: objective-c
before_script: travis/before_script.sh
script: travis/script.sh
deploy:
  provider: releases
  api_key:
    secure: "M1N6Oj9SaLDH0oxWncsJ9ePX3B2SdVAsJt9FGEJVwEUcOg7spGl371VISKwcbV0uy+DWGyldum1kldXmnf/fT20IwJ3b1hnGAzxuA2IhgiuP00nmK4XzlnmYpW72+Kvq7OPg2XHtFie/ZswXAmPD0bv8emSKf2DGFBxPEP7F+7k="
  file: Gameeso-iOS-SDK.zip
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    repo: Gameeso/openkit-ios